apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-deploy
  name: helm-deploy-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helm-deploy
  type: ClusterIP
