apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    name: myapp
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx

  tolerations:
    - key: "spray"
      value: "mortein"
      operator: "Equal"
      effect: NoSchedule