apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels:
    type: front-end
spec:
  selector:
    matchLabels:
      type: front-end
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
        
    