apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: LoadBalancer
  selector:
    name: mongo-express
  ports:
    - targetPort: 8081
      port: 8081
      protocol: TCP
      nodePort: 30008