apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
  labels:
    name: myapp
spec:
  containers:
  - name: secret-container-xfusion
    image: fedora:latest
    command:
      - "sleep"
      - "20000"
    volumeMounts:
      - name: test
        mountPath: /opt/cluster
        readOnly: true
  volumes:
    - name: test
      secret:
        secretName: ecommerce



kubectl create secret generic test --from-file=/opt/ecommerce.txt
