apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-proje
spec:
  replicas: 2
  selector:
    matchLabels:
      name: httpd-frontend
  template:
    metadata:
      labels:
        name: httpd-frontend
    spec:
      containers:
        - name: node-container
          image: gcr.io/kodekloud/centos-ssh-enabled:node
  
---

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    name: httpd-frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30012
    

